
package com.qk365.base.webservice.client.oa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5 2015-09-29T14:36:24.451+08:00
 * Generated source version: 2.7.5
 * 
 */
public final class ISecurityServices_SecurityServicesImplPort_Client {

	private static final QName SERVICE_NAME = new QName("http://impl.Security.WebService.jdnet.com/",
			"SecurityService");

	private ISecurityServices_SecurityServicesImplPort_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = SecurityService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		SecurityService ss = new SecurityService(wsdlURL, SERVICE_NAME);
		ISecurityServices port = ss.getSecurityServicesImplPort();

		{
			System.out.println("Invoking login...");
			java.lang.String _login_arg0 = "";
			java.lang.String _login_arg1 = "";
			java.lang.String _login_arg2 = "";
			java.lang.String _login__return = port.login(_login_arg0, _login_arg1, _login_arg2);
			System.out.println("login.result=" + _login__return);

		}
		{
			System.out.println("Invoking modifyPassword...");
			java.lang.String _modifyPassword_arg0 = "";
			java.lang.String _modifyPassword_arg1 = "";
			java.lang.String _modifyPassword_arg2 = "";
			java.lang.String _modifyPassword__return = port.modifyPassword(_modifyPassword_arg0, _modifyPassword_arg1,
					_modifyPassword_arg2);
			System.out.println("modifyPassword.result=" + _modifyPassword__return);

		}
		{
			System.out.println("Invoking login2...");
			java.lang.String _login2_arg0 = "";
			java.lang.String _login2_arg1 = "";
			java.lang.String _login2_arg2 = "";
			java.lang.String _login2__return = port.login2(_login2_arg0, _login2_arg1, _login2_arg2);
			System.out.println("login2.result=" + _login2__return);

		}
		{
			System.out.println("Invoking login3...");
			java.lang.String _login3_arg0 = "";
			java.lang.String _login3_arg1 = "";
			java.lang.String _login3_arg2 = "";
			java.lang.String _login3__return = port.login3(_login3_arg0, _login3_arg1, _login3_arg2);
			System.out.println("login3.result=" + _login3__return);

		}

		System.exit(0);
	}

}
