package com.qk365.base.webservice.client.oa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2015-09-29T14:36:24.491+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://inter.Security.WebService.jdnet.com/", name = "ISecurityServices")
@XmlSeeAlso({ObjectFactory.class})
public interface ISecurityServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.LoginResponse")
    public java.lang.String login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "modifyPassword", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.ModifyPassword")
    @WebMethod
    @ResponseWrapper(localName = "modifyPasswordResponse", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.ModifyPasswordResponse")
    public java.lang.String modifyPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login2", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.Login2")
    @WebMethod
    @ResponseWrapper(localName = "login2Response", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.Login2Response")
    public java.lang.String login2(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login3", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.Login3")
    @WebMethod
    @ResponseWrapper(localName = "login3Response", targetNamespace = "http://inter.Security.WebService.jdnet.com/", className = "com.qk365.webservice.client.oa.Login3Response")
    public java.lang.String login3(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
