package com.qk365.sample.core;

import java.math.BigDecimal;
import java.util.Date;

public class SampleBean {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutId;

	@Override
	public String toString() {
		return "SampleBean [cutId=" + cutId + ", cutContactName=" + cutContactName + "]";
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Password
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutPassword;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Voucher_No
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutVoucherNo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Contact_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutContactName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Honesty_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutHonestyPoint;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Mark
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutMark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_State
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutState;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Login_Date
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Date cutLoginDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Balance
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private BigDecimal cutBalance;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.VO_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer voId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_PER_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutPerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Create_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Date cutCreateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.AutoPay
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer autopay;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Sincerity_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutSincerityPoint;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_OtherRMB
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private BigDecimal cutOtherrmb;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Tenant_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutTenantMobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Email
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutEmail;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Political_Landscape
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private String cutPoliticalLandscape;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Grade
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutGrade;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.cut_src
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutSrc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.cut_is_perfect
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutIsPerfect;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.cut_per_test
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutPerTest;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.cut_IsInfoComplete
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutIsinfocomplete;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_Update_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Date cutUpdateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column Customer_Tenant.CUT_IsValidate
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	private Integer cutIsvalidate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Id
	 *
	 * @return the value of Customer_Tenant.CUT_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutId() {
		return cutId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Id
	 *
	 * @param cutId
	 *            the value for Customer_Tenant.CUT_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutId(Integer cutId) {
		this.cutId = cutId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Name
	 *
	 * @return the value of Customer_Tenant.CUT_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutName() {
		return cutName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Name
	 *
	 * @param cutName
	 *            the value for Customer_Tenant.CUT_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutName(String cutName) {
		this.cutName = cutName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Password
	 *
	 * @return the value of Customer_Tenant.CUT_Password
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutPassword() {
		return cutPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Password
	 *
	 * @param cutPassword
	 *            the value for Customer_Tenant.CUT_Password
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutPassword(String cutPassword) {
		this.cutPassword = cutPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Voucher_No
	 *
	 * @return the value of Customer_Tenant.CUT_Voucher_No
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutVoucherNo() {
		return cutVoucherNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Voucher_No
	 *
	 * @param cutVoucherNo
	 *            the value for Customer_Tenant.CUT_Voucher_No
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutVoucherNo(String cutVoucherNo) {
		this.cutVoucherNo = cutVoucherNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Contact_Name
	 *
	 * @return the value of Customer_Tenant.CUT_Contact_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutContactName() {
		return cutContactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Contact_Name
	 *
	 * @param cutContactName
	 *            the value for Customer_Tenant.CUT_Contact_Name
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutContactName(String cutContactName) {
		this.cutContactName = cutContactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Mobile
	 *
	 * @return the value of Customer_Tenant.CUT_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutMobile() {
		return cutMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Mobile
	 *
	 * @param cutMobile
	 *            the value for Customer_Tenant.CUT_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutMobile(String cutMobile) {
		this.cutMobile = cutMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Honesty_Point
	 *
	 * @return the value of Customer_Tenant.CUT_Honesty_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutHonestyPoint() {
		return cutHonestyPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Honesty_Point
	 *
	 * @param cutHonestyPoint
	 *            the value for Customer_Tenant.CUT_Honesty_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutHonestyPoint(Integer cutHonestyPoint) {
		this.cutHonestyPoint = cutHonestyPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Mark
	 *
	 * @return the value of Customer_Tenant.CUT_Mark
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutMark() {
		return cutMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Mark
	 *
	 * @param cutMark
	 *            the value for Customer_Tenant.CUT_Mark
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutMark(String cutMark) {
		this.cutMark = cutMark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_State
	 *
	 * @return the value of Customer_Tenant.CUT_State
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutState() {
		return cutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_State
	 *
	 * @param cutState
	 *            the value for Customer_Tenant.CUT_State
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutState(Integer cutState) {
		this.cutState = cutState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Login_Date
	 *
	 * @return the value of Customer_Tenant.CUT_Login_Date
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Date getCutLoginDate() {
		return cutLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Login_Date
	 *
	 * @param cutLoginDate
	 *            the value for Customer_Tenant.CUT_Login_Date
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutLoginDate(Date cutLoginDate) {
		this.cutLoginDate = cutLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Balance
	 *
	 * @return the value of Customer_Tenant.CUT_Balance
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public BigDecimal getCutBalance() {
		return cutBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Balance
	 *
	 * @param cutBalance
	 *            the value for Customer_Tenant.CUT_Balance
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutBalance(BigDecimal cutBalance) {
		this.cutBalance = cutBalance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.VO_Id
	 *
	 * @return the value of Customer_Tenant.VO_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getVoId() {
		return voId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.VO_Id
	 *
	 * @param voId
	 *            the value for Customer_Tenant.VO_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setVoId(Integer voId) {
		this.voId = voId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_PER_Id
	 *
	 * @return the value of Customer_Tenant.CUT_PER_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutPerId() {
		return cutPerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_PER_Id
	 *
	 * @param cutPerId
	 *            the value for Customer_Tenant.CUT_PER_Id
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutPerId(Integer cutPerId) {
		this.cutPerId = cutPerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Create_Time
	 *
	 * @return the value of Customer_Tenant.CUT_Create_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Date getCutCreateTime() {
		return cutCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Create_Time
	 *
	 * @param cutCreateTime
	 *            the value for Customer_Tenant.CUT_Create_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutCreateTime(Date cutCreateTime) {
		this.cutCreateTime = cutCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.AutoPay
	 *
	 * @return the value of Customer_Tenant.AutoPay
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getAutopay() {
		return autopay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.AutoPay
	 *
	 * @param autopay
	 *            the value for Customer_Tenant.AutoPay
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setAutopay(Integer autopay) {
		this.autopay = autopay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Sincerity_Point
	 *
	 * @return the value of Customer_Tenant.CUT_Sincerity_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutSincerityPoint() {
		return cutSincerityPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Sincerity_Point
	 *
	 * @param cutSincerityPoint
	 *            the value for Customer_Tenant.CUT_Sincerity_Point
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutSincerityPoint(String cutSincerityPoint) {
		this.cutSincerityPoint = cutSincerityPoint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_OtherRMB
	 *
	 * @return the value of Customer_Tenant.CUT_OtherRMB
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public BigDecimal getCutOtherrmb() {
		return cutOtherrmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_OtherRMB
	 *
	 * @param cutOtherrmb
	 *            the value for Customer_Tenant.CUT_OtherRMB
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutOtherrmb(BigDecimal cutOtherrmb) {
		this.cutOtherrmb = cutOtherrmb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Tenant_Mobile
	 *
	 * @return the value of Customer_Tenant.CUT_Tenant_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutTenantMobile() {
		return cutTenantMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Tenant_Mobile
	 *
	 * @param cutTenantMobile
	 *            the value for Customer_Tenant.CUT_Tenant_Mobile
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutTenantMobile(String cutTenantMobile) {
		this.cutTenantMobile = cutTenantMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Email
	 *
	 * @return the value of Customer_Tenant.CUT_Email
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutEmail() {
		return cutEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Email
	 *
	 * @param cutEmail
	 *            the value for Customer_Tenant.CUT_Email
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutEmail(String cutEmail) {
		this.cutEmail = cutEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Political_Landscape
	 *
	 * @return the value of Customer_Tenant.CUT_Political_Landscape
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public String getCutPoliticalLandscape() {
		return cutPoliticalLandscape;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Political_Landscape
	 *
	 * @param cutPoliticalLandscape
	 *            the value for Customer_Tenant.CUT_Political_Landscape
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutPoliticalLandscape(String cutPoliticalLandscape) {
		this.cutPoliticalLandscape = cutPoliticalLandscape;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Grade
	 *
	 * @return the value of Customer_Tenant.CUT_Grade
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutGrade() {
		return cutGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Grade
	 *
	 * @param cutGrade
	 *            the value for Customer_Tenant.CUT_Grade
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutGrade(Integer cutGrade) {
		this.cutGrade = cutGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.cut_src
	 *
	 * @return the value of Customer_Tenant.cut_src
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutSrc() {
		return cutSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.cut_src
	 *
	 * @param cutSrc
	 *            the value for Customer_Tenant.cut_src
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutSrc(Integer cutSrc) {
		this.cutSrc = cutSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.cut_is_perfect
	 *
	 * @return the value of Customer_Tenant.cut_is_perfect
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutIsPerfect() {
		return cutIsPerfect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.cut_is_perfect
	 *
	 * @param cutIsPerfect
	 *            the value for Customer_Tenant.cut_is_perfect
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutIsPerfect(Integer cutIsPerfect) {
		this.cutIsPerfect = cutIsPerfect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.cut_per_test
	 *
	 * @return the value of Customer_Tenant.cut_per_test
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutPerTest() {
		return cutPerTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.cut_per_test
	 *
	 * @param cutPerTest
	 *            the value for Customer_Tenant.cut_per_test
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutPerTest(Integer cutPerTest) {
		this.cutPerTest = cutPerTest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.cut_IsInfoComplete
	 *
	 * @return the value of Customer_Tenant.cut_IsInfoComplete
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutIsinfocomplete() {
		return cutIsinfocomplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.cut_IsInfoComplete
	 *
	 * @param cutIsinfocomplete
	 *            the value for Customer_Tenant.cut_IsInfoComplete
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutIsinfocomplete(Integer cutIsinfocomplete) {
		this.cutIsinfocomplete = cutIsinfocomplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_Update_Time
	 *
	 * @return the value of Customer_Tenant.CUT_Update_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Date getCutUpdateTime() {
		return cutUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_Update_Time
	 *
	 * @param cutUpdateTime
	 *            the value for Customer_Tenant.CUT_Update_Time
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutUpdateTime(Date cutUpdateTime) {
		this.cutUpdateTime = cutUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column Customer_Tenant.CUT_IsValidate
	 *
	 * @return the value of Customer_Tenant.CUT_IsValidate
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public Integer getCutIsvalidate() {
		return cutIsvalidate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column Customer_Tenant.CUT_IsValidate
	 *
	 * @param cutIsvalidate
	 *            the value for Customer_Tenant.CUT_IsValidate
	 *
	 * @mbggenerated Tue Oct 13 16:14:36 CST 2015
	 */
	public void setCutIsvalidate(Integer cutIsvalidate) {
		this.cutIsvalidate = cutIsvalidate;
	}
}