package com.qk365.domain;

import com.qk365.base.persist.base.ISqlMapper;
import com.qk365.domain.Provincial;
import com.qk365.domain.ProvincialExample;
import com.qk365.sample.core.SampleBean;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvincialMapper  extends ISqlMapper<Provincial, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int countByExample(ProvincialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int deleteByExample(ProvincialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int deleteByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int insert(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int insertSelective(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    List<Provincial> selectByExample(ProvincialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    Provincial selectByPrimaryKey(Integer prcId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int updateByExampleSelective(@Param("record") Provincial record, @Param("example") ProvincialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int updateByExample(@Param("record") Provincial record, @Param("example") ProvincialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int updateByPrimaryKeySelective(Provincial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    int updateByPrimaryKey(Provincial record);
}