package com.qk365.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.qk365.base.persist.base.IModelExample;

public class ProvincialExample implements IModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public ProvincialExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrcIdIsNull() {
            addCriterion("PRC_Id is null");
            return (Criteria) this;
        }

        public Criteria andPrcIdIsNotNull() {
            addCriterion("PRC_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPrcIdEqualTo(Integer value) {
            addCriterion("PRC_Id =", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdNotEqualTo(Integer value) {
            addCriterion("PRC_Id <>", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdGreaterThan(Integer value) {
            addCriterion("PRC_Id >", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRC_Id >=", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdLessThan(Integer value) {
            addCriterion("PRC_Id <", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRC_Id <=", value, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdIn(List<Integer> values) {
            addCriterion("PRC_Id in", values, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdNotIn(List<Integer> values) {
            addCriterion("PRC_Id not in", values, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdBetween(Integer value1, Integer value2) {
            addCriterion("PRC_Id between", value1, value2, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRC_Id not between", value1, value2, "prcId");
            return (Criteria) this;
        }

        public Criteria andPrcNameIsNull() {
            addCriterion("PRC_Name is null");
            return (Criteria) this;
        }

        public Criteria andPrcNameIsNotNull() {
            addCriterion("PRC_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPrcNameEqualTo(String value) {
            addCriterion("PRC_Name =", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameNotEqualTo(String value) {
            addCriterion("PRC_Name <>", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameGreaterThan(String value) {
            addCriterion("PRC_Name >", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameGreaterThanOrEqualTo(String value) {
            addCriterion("PRC_Name >=", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameLessThan(String value) {
            addCriterion("PRC_Name <", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameLessThanOrEqualTo(String value) {
            addCriterion("PRC_Name <=", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameLike(String value) {
            addCriterion("PRC_Name like", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameNotLike(String value) {
            addCriterion("PRC_Name not like", value, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameIn(List<String> values) {
            addCriterion("PRC_Name in", values, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameNotIn(List<String> values) {
            addCriterion("PRC_Name not in", values, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameBetween(String value1, String value2) {
            addCriterion("PRC_Name between", value1, value2, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcNameNotBetween(String value1, String value2) {
            addCriterion("PRC_Name not between", value1, value2, "prcName");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdIsNull() {
            addCriterion("PRC_Parent_Id is null");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdIsNotNull() {
            addCriterion("PRC_Parent_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdEqualTo(Integer value) {
            addCriterion("PRC_Parent_Id =", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdNotEqualTo(Integer value) {
            addCriterion("PRC_Parent_Id <>", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdGreaterThan(Integer value) {
            addCriterion("PRC_Parent_Id >", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRC_Parent_Id >=", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdLessThan(Integer value) {
            addCriterion("PRC_Parent_Id <", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRC_Parent_Id <=", value, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdIn(List<Integer> values) {
            addCriterion("PRC_Parent_Id in", values, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdNotIn(List<Integer> values) {
            addCriterion("PRC_Parent_Id not in", values, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdBetween(Integer value1, Integer value2) {
            addCriterion("PRC_Parent_Id between", value1, value2, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRC_Parent_Id not between", value1, value2, "prcParentId");
            return (Criteria) this;
        }

        public Criteria andPrcCodeIsNull() {
            addCriterion("PRC_Code is null");
            return (Criteria) this;
        }

        public Criteria andPrcCodeIsNotNull() {
            addCriterion("PRC_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPrcCodeEqualTo(String value) {
            addCriterion("PRC_Code =", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeNotEqualTo(String value) {
            addCriterion("PRC_Code <>", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeGreaterThan(String value) {
            addCriterion("PRC_Code >", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRC_Code >=", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeLessThan(String value) {
            addCriterion("PRC_Code <", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeLessThanOrEqualTo(String value) {
            addCriterion("PRC_Code <=", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeLike(String value) {
            addCriterion("PRC_Code like", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeNotLike(String value) {
            addCriterion("PRC_Code not like", value, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeIn(List<String> values) {
            addCriterion("PRC_Code in", values, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeNotIn(List<String> values) {
            addCriterion("PRC_Code not in", values, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeBetween(String value1, String value2) {
            addCriterion("PRC_Code between", value1, value2, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcCodeNotBetween(String value1, String value2) {
            addCriterion("PRC_Code not between", value1, value2, "prcCode");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdIsNull() {
            addCriterion("PRC_PER_Id is null");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdIsNotNull() {
            addCriterion("PRC_PER_Id is not null");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdEqualTo(Integer value) {
            addCriterion("PRC_PER_Id =", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdNotEqualTo(Integer value) {
            addCriterion("PRC_PER_Id <>", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdGreaterThan(Integer value) {
            addCriterion("PRC_PER_Id >", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRC_PER_Id >=", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdLessThan(Integer value) {
            addCriterion("PRC_PER_Id <", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRC_PER_Id <=", value, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdIn(List<Integer> values) {
            addCriterion("PRC_PER_Id in", values, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdNotIn(List<Integer> values) {
            addCriterion("PRC_PER_Id not in", values, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdBetween(Integer value1, Integer value2) {
            addCriterion("PRC_PER_Id between", value1, value2, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcPerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRC_PER_Id not between", value1, value2, "prcPerId");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeIsNull() {
            addCriterion("PRC_Create_Time is null");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeIsNotNull() {
            addCriterion("PRC_Create_Time is not null");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeEqualTo(Date value) {
            addCriterion("PRC_Create_Time =", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeNotEqualTo(Date value) {
            addCriterion("PRC_Create_Time <>", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeGreaterThan(Date value) {
            addCriterion("PRC_Create_Time >", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PRC_Create_Time >=", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeLessThan(Date value) {
            addCriterion("PRC_Create_Time <", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("PRC_Create_Time <=", value, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeIn(List<Date> values) {
            addCriterion("PRC_Create_Time in", values, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeNotIn(List<Date> values) {
            addCriterion("PRC_Create_Time not in", values, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeBetween(Date value1, Date value2) {
            addCriterion("PRC_Create_Time between", value1, value2, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andPrcCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("PRC_Create_Time not between", value1, value2, "prcCreateTime");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeIsNull() {
            addCriterion("CUC_Longitude is null");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeIsNotNull() {
            addCriterion("CUC_Longitude is not null");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeEqualTo(BigDecimal value) {
            addCriterion("CUC_Longitude =", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("CUC_Longitude <>", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeGreaterThan(BigDecimal value) {
            addCriterion("CUC_Longitude >", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CUC_Longitude >=", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeLessThan(BigDecimal value) {
            addCriterion("CUC_Longitude <", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CUC_Longitude <=", value, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeIn(List<BigDecimal> values) {
            addCriterion("CUC_Longitude in", values, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("CUC_Longitude not in", values, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUC_Longitude between", value1, value2, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUC_Longitude not between", value1, value2, "cucLongitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeIsNull() {
            addCriterion("CUC_Latitude is null");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeIsNotNull() {
            addCriterion("CUC_Latitude is not null");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeEqualTo(BigDecimal value) {
            addCriterion("CUC_Latitude =", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("CUC_Latitude <>", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeGreaterThan(BigDecimal value) {
            addCriterion("CUC_Latitude >", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CUC_Latitude >=", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeLessThan(BigDecimal value) {
            addCriterion("CUC_Latitude <", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CUC_Latitude <=", value, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeIn(List<BigDecimal> values) {
            addCriterion("CUC_Latitude in", values, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("CUC_Latitude not in", values, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUC_Latitude between", value1, value2, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andCucLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CUC_Latitude not between", value1, value2, "cucLatitude");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andPrcIndexIsNull() {
            addCriterion("prc_index is null");
            return (Criteria) this;
        }

        public Criteria andPrcIndexIsNotNull() {
            addCriterion("prc_index is not null");
            return (Criteria) this;
        }

        public Criteria andPrcIndexEqualTo(Integer value) {
            addCriterion("prc_index =", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexNotEqualTo(Integer value) {
            addCriterion("prc_index <>", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexGreaterThan(Integer value) {
            addCriterion("prc_index >", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("prc_index >=", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexLessThan(Integer value) {
            addCriterion("prc_index <", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexLessThanOrEqualTo(Integer value) {
            addCriterion("prc_index <=", value, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexIn(List<Integer> values) {
            addCriterion("prc_index in", values, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexNotIn(List<Integer> values) {
            addCriterion("prc_index not in", values, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexBetween(Integer value1, Integer value2) {
            addCriterion("prc_index between", value1, value2, "prcIndex");
            return (Criteria) this;
        }

        public Criteria andPrcIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("prc_index not between", value1, value2, "prcIndex");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Provincial
     *
     * @mbggenerated do_not_delete_during_merge Fri Oct 16 18:36:02 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Provincial
     *
     * @mbggenerated Fri Oct 16 18:36:02 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}